#!/bin/bash
#
# Read in the configuration.
plugin="file.activity"
CONFIG="/boot/config/plugins/${plugin}/${plugin}.cfg"
source $CONFIG

# Start file activity if it is enabled.
if [ "$SERVICE" = "enable" ]; then
	echo "/usr/local/emhttp/plugins/${plugin}/scripts/rc.${plugin} start" | at now + 2 minutes > /dev/null 2>&1
fi
