#!/bin/bash
#
# Copyright 2020-2025 Dan Landon
#
# Permission is granted to use this software for personal, educational, or internal use only.
# Commercial use, redistribution, or modification of this software or any derived works
# is strictly prohibited without prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
#

# Read in the configuration.
plugin="file.activity"
CONFIG="/boot/config/plugins/${plugin}/${plugin}.cfg"
source $CONFIG

# Start file activity if it is enabled.
if [ "$SERVICE" = "enable" ]; then
	/usr/local/emhttp/plugins/${plugin}/scripts/rc.${plugin} start 10 >/dev/null 2>&1 &
fi
