#!/bin/bash
#
# Read in the configuration.
plugin="file.activity"
CONFIG="/boot/config/plugins/${plugin}/${plugin}.cfg"
source $CONFIG

# Start file activity if it is enabled.
if [ "$SERVICE" = "enable" ]; then
	/usr/local/emhttp/plugins/${plugin}/scripts/rc.${plugin} start 1>/dev/null
fi
