#!/bin/bash
#
# Copyright 2020-2025 Dan Landon
#
# Permission is granted to use this software for personal, educational, or internal use only.
# Commercial use, redistribution, or modification of this software or any derived works
# is strictly prohibited without prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
#

plugin="file.activity"

# Stop file activity logging if it is running.
if [ -e "/var/run/${plugin}.pid" ]; then
	/usr/local/emhttp/plugins/${plugin}/scripts/rc.${plugin} stop >/dev/null 2>&1 &
fi
