#!/usr/bin/php
<?php
/* Copyright 2020-2025, Dan Landon
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */

/* Define our plugin name. */
if (!defined('FILE_ACTIVITY_PLUGIN')) {
	define('FILE_ACTIVITY_PLUGIN', 'file.activity');
}

/* Define the docroot path. */
if (!defined('DOCROOT')) {
	define('DOCROOT', $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp');
}

$disks			= @parse_ini_file(DOCROOT."/state/disks.ini", true);
$disks_file		="/tmp/".FILE_ACTIVITY_PLUGIN."/".FILE_ACTIVITY_PLUGIN.".disks";

/* See if UD is installed */
if (file_exists("plugins/unassigned.devices/include/lib.php")) {
	require_once("plugins/unassigned.devices/include/lib.php");
	$UD_installed = true;
} else {
	$UD_installed = false;
}	

$excluded_names = array("parity", "parity2", "flash");

$INCLUDE_SSD	= (isset($argv[1])) ? $argv[1] : "no";
$INCLUDE_UD		= (isset($argv[2])) ? $argv[2] : "no";
$INCLUDE_CACHE	= (isset($argv[3])) ? $argv[3] : "no";

function is_array_disk($var) {
	/* An array or pool disk is any disk not starting with 'parity' or 'flash' */
	$rc = true;

	if (strpos($var, 'parity') === 0 || strpos($var, 'flash') === 0)
		$rc = false;

	return $rc;
}

/* Get all unraid disk devices (array disks, cache, and pool devices) */
$all_disks = array();
foreach ($disks as $key => $val) {
	/* Only monitor rotational devices for file activity if enabled. */
	if (is_dir("/mnt/".$key."/") && (($val['rotational'] == "1") || (($val['rotational'] == "0") && ($INCLUDE_SSD == "yes")))) {
		$all_disks[] = $key;
	}
}

$array_disks = array_filter($all_disks, "is_array_disk");
$pool_disks = array_diff($all_disks, $excluded_names);
$pool_disks = array_diff($pool_disks, $array_disks);

/* Initialize the UD devices array. */
$ud_array = array();

/* Add UD devices if UD installed and include UD disks is enabled. */
if (($UD_installed) && ($INCLUDE_UD == "yes")) {
	/* Get all the UD disks. */
	$ud_disks	= get_all_disks_info();

	foreach ($ud_disks as $key => $val) {
		/* Skip UD device if there are no partitions. */
		if ($val['partitions']) {
			/* Only monitor mounted rotational devices for file activity if enabled. */
			if (($val['partitions'][0]['mounted']) && ((! $val['ssd']) || (($val['ssd']) && ($INCLUDE_SSD == "yes")))) {
				$ud_array[]	= "disks/".basename($val['partitions'][0]['mountpoint']);
			}
		}
	}
}

if ($INCLUDE_CACHE == "no") {
	$pool_disks = array();
}
$disks_array = array_merge($array_disks, $pool_disks);
$disks_array = array_merge($disks_array, $ud_array);

$disks_text = "";
foreach ($disks_array as $disk) {
	$disks_text .= "/mnt/".$disk."\n";
}

file_put_contents($disks_file, $disks_text);
?>
